// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	consumer "github.com/project-eria/go-wot/consumer"
	interaction "github.com/project-eria/go-wot/interaction"

	mock "github.com/stretchr/testify/mock"
)

// ProtocolClient is an autogenerated mock type for the ProtocolClient type
type ProtocolClient struct {
	mock.Mock
}

// GetSchemes provides a mock function with given fields:
func (_m *ProtocolClient) GetSchemes() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSchemes")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// InvokeResource provides a mock function with given fields: _a0, _a1, _a2
func (_m *ProtocolClient) InvokeResource(_a0 *interaction.Form, _a1 map[string]interface{}, _a2 interface{}) (interface{}, string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for InvokeResource")
	}

	var r0 interface{}
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}, interface{}) (interface{}, string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}, interface{}) interface{}); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*interaction.Form, map[string]interface{}, interface{}) string); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*interaction.Form, map[string]interface{}, interface{}) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReadResource provides a mock function with given fields: _a0, _a1
func (_m *ProtocolClient) ReadResource(_a0 *interaction.Form, _a1 map[string]interface{}) (interface{}, string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReadResource")
	}

	var r0 interface{}
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}) (interface{}, string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}) interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*interaction.Form, map[string]interface{}) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*interaction.Form, map[string]interface{}) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Stop provides a mock function with given fields:
func (_m *ProtocolClient) Stop() {
	_m.Called()
}

// SubscribeResource provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *ProtocolClient) SubscribeResource(_a0 *interaction.Form, _a1 map[string]interface{}, _a2 *consumer.Subscription, _a3 consumer.Listener) (string, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeResource")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}, *consumer.Subscription, consumer.Listener) (string, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}, *consumer.Subscription, consumer.Listener) string); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*interaction.Form, map[string]interface{}, *consumer.Subscription, consumer.Listener) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteResource provides a mock function with given fields: _a0, _a1, _a2
func (_m *ProtocolClient) WriteResource(_a0 *interaction.Form, _a1 map[string]interface{}, _a2 interface{}) (interface{}, string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for WriteResource")
	}

	var r0 interface{}
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}, interface{}) (interface{}, string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(*interaction.Form, map[string]interface{}, interface{}) interface{}); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*interaction.Form, map[string]interface{}, interface{}) string); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*interaction.Form, map[string]interface{}, interface{}) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewProtocolClient creates a new instance of ProtocolClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProtocolClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProtocolClient {
	mock := &ProtocolClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
