// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecurityScheme is an autogenerated mock type for the SecurityScheme type
type SecurityScheme struct {
	mock.Mock
}

// NewSecurityScheme creates a new instance of SecurityScheme. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityScheme(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityScheme {
	mock := &SecurityScheme{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
